{ config, pkgs, inputs, ... }:

{
  home.username = "bugzy";
  home.homeDirectory = "/home/bugzy";
  home.stateVersion = "25.11";

  # pipx-installed binaries live here
  home.sessionPath = [ "$HOME/.local/bin" ];

  # Let Home Manager manage itself
  programs.home-manager.enable = true;

  # ── Packages ─────────────────────────────────────────────────────────────
  nixpkgs.config.allowUnfree = true;

  home.packages = with pkgs; [
    firefox
    spotdl
    mako
    aria2
    yt-dlp
    ffmpeg
    fzf
    openssl
    ani-skip
    ani-cli
    terminaltexteffects
    mpv
    mpvpaper
    pywal16
    waypaper
    riseup-vpn
    prismlauncher
    lxqt.lxqt-policykit
    steam
    pavucontrol
    vscode
    discord
    audacity
    blender
    godot
    wl-clipboard
    kdePackages.dolphin
    kitty
    unzip
    unrar
    waybar
    kew
    nodejs
    pkg-config
    openssl
    libimobiledevice
    usbmuxd
    glib
    gtk3
    webkitgtk_4_1
    gsettings-desktop-schemas
    vim
    wget
    git
    bibata-cursors
    papirus-icon-theme
    rofi
    bluez
    blueman
    playerctl
    brightnessctl
    jetbrains-mono
    swaybg
    claude-code
    neovim
    cmatrix
    cava
    ripgrep
    fd
    gcc
    lazygit
    grim
    slurp
    appimage-run
    usbmuxd
    openssl
    python3
    curl
    
  ];
 
  programs.obs-studio = {
   enable = true;
   plugins = with pkgs.obs-studio-plugins; [
   obs-pipewire-audio-capture
   obs-vkcapture
   obs-vaapi
   obs-gstreamer
   wlrobs
 ];
};   

  # kitty
  programs.kitty = {
    enable = true;
    settings = {
      allow_remote_control = "yes";
    };
    # Pull colors from pywal's generated palette so new kitty windows
    # match the current wallpaper. Regenerated by wallpaper-colors.py.
    # background_opacity comes *after* the include so wal's "1.0" doesn't
    # win — we want a fully transparent background.
    extraConfig = ''
      include ${config.home.homeDirectory}/.cache/wal/colors-kitty.conf
      background_opacity 0
    '';
  };

  # ── Fastfetch ─────────────────────────────────────────────────────────────
  programs.fastfetch = {
    enable = true;
    settings = {
      logo = {
        source = "nixos_small";
        padding.right = 2;
      };
      modules = [
        "title"
        "separator"
        { type = "os";       key = "OS";      }
        { type = "kernel";   key = "Kernel";  }
        { type = "uptime";   key = "Uptime";  }
        { type = "shell";    key = "Shell";   }
        "separator"
      ];
    };
  };

  # ── Shell ─────────────────────────────────────────────────────────────────
  programs.bash = {
    enable = true;
    initExtra = "fastfetch";
  };

  # ── Git ───────────────────────────────────────────────────────────────────
  programs.git = {
    enable = true;
    settings = {
      user.name = "Bugzymp4";
      user.email = "bugzyrecordz@gmail.com";
      init.defaultBranch = "master";
    };
  };

  # ── Waybar ────────────────────────────────────────────────────────────────
  # Warm fractal theme: amber/gold body, teal veining, copper depths, chartreuse
  # highlights — palette pulled from Pictures/wallpapers/nixos.png. Floating-
  # island layout: bar is transparent, each module group is its own pill.
  programs.waybar = {
    enable = true;
    settings = [{
      layer = "top";
      position = "top";
      height = 44;
      spacing = 0;

      modules-left   = [ "ext/workspaces" ];
      modules-center = [ "clock" ];
      modules-right  = [ "mpd" "pulseaudio" "cpu" "memory" "network" "tray" ];

      "ext/workspaces" = {
        format = "{name}";
        on-click = "activate";
        sort-by-id = true;
      };

      clock = {
        interval = 1;
        format = "<span weight='bold'>{0:%H:%M:%S}</span>\n<span size='x-small' alpha='55%'>{0:%a · %b %d}</span>";
        tooltip-format = "<tt>{calendar}</tt>";
      };

      mpd = {
        format = "♪ {title} — {artist}";
        format-disconnected = "♪ —";
        format-stopped = "♪ stopped";
        format-paused = "♪ {title}";
        interval = 2;
        max-length = 40;
        on-click = "playerctl play-pause";
        on-scroll-up = "playerctl next";
        on-scroll-down = "playerctl previous";
      };

      pulseaudio = {
        format = "♫ {volume}%";
        format-muted = "♫ mute";
        on-click = "pactl set-sink-mute @DEFAULT_SINK@ toggle";
        on-scroll-up = "pactl set-sink-volume @DEFAULT_SINK@ +2%";
        on-scroll-down = "pactl set-sink-volume @DEFAULT_SINK@ -2%";
        tooltip = false;
      };

      cpu = {
        interval = 3;
        format = "◆ {usage}%";
        max-length = 10;
        states = { warning = 70; critical = 90; };
      };

      memory = {
        interval = 10;
        format = "▣ {used:0.1f}G";
        max-length = 10;
        states = { warning = 75; critical = 90; };
      };

      network = {
        format-wifi = "≋ {signalStrength}%";
        format-ethernet = "≋ eth";
        format-disconnected = "≋ off";
        tooltip-format-wifi = "{essid}\n{ipaddr}";
        max-length = 14;
      };

      tray = {
        icon-size = 16;
        spacing = 8;
      };
    }];

    style = ''
      @import "/home/bugzy/.config/waybar/colors.css";

      * {
          font-family: "JetBrains Mono", monospace;
          font-size: 11px;
          font-weight: 500;
          border: none;
          border-radius: 0;
          min-height: 0;
      }

      /* ── bar shell (transparent — islands float on top) ─────────────── */
      window#waybar {
          background: transparent;
          color: @cream;
      }

      window#waybar > box {
          background: transparent;
      }

      /* ── floating islands ───────────────────────────────────────────── */
      .modules-left,
      .modules-center,
      .modules-right {
          background: @island_bg;
          border: 1px solid alpha(@teal, 0.45);
          border-radius: 14px;
          padding: 0 6px;
          margin: 6px 10px;
      }

      .modules-center {
          animation: shimmer 7s ease-in-out infinite;
      }

      @keyframes shimmer {
          0%   { border-color: alpha(@teal,       0.40); }
          33%  { border-color: alpha(@amber,      0.55); }
          66%  { border-color: alpha(@chartreuse, 0.50); }
          100% { border-color: alpha(@teal,       0.40); }
      }

      /* ── workspaces ─────────────────────────────────────────────────── */
      #workspaces {
          background: transparent;
          padding: 0 4px;
      }

      #workspaces button {
          color: @text_dim;
          background: transparent;
          padding: 2px 10px;
          margin: 4px 2px;
          border-radius: 6px;
          font-weight: 600;
          letter-spacing: 0.08em;
          transition: all 0.18s ease;
          min-width: 22px;
      }

      #workspaces button:hover {
          color: @gold;
          background: alpha(@amber, 0.12);
      }

      #workspaces button.active {
          color: @cream;
          background: linear-gradient(135deg,
              alpha(@teal,   0.40) 0%,
              alpha(@amber,  0.30) 55%,
              alpha(@copper, 0.22) 100%);
          box-shadow: 0 0 8px alpha(@teal_bright, 0.55),
                      inset 0 0 4px alpha(@teal_bright, 0.30);
      }

      /* ── clock (center) ─────────────────────────────────────────────── */
      #clock {
          color: @teal_bright;
          text-shadow: 0 0 6px alpha(@amber, 0.55);
          padding: 2px 18px;
          margin: 3px 3px;
          border-radius: 10px;
          letter-spacing: 0.06em;
      }

      /* ── right-side module pills ────────────────────────────────────── */
      #cpu,
      #memory,
      #network,
      #pulseaudio,
      #mpd {
          padding: 2px 11px;
          margin: 4px 3px;
          border-radius: 8px;
          border: 1px solid transparent;
          letter-spacing: 0.04em;
          transition: all 0.18s ease;
      }

      #cpu {
          color: @chartreuse;
          background: alpha(@chartreuse, 0.08);
          border-color: alpha(@chartreuse, 0.35);
      }

      #memory {
          color: @copper;
          background: alpha(@copper, 0.10);
          border-color: alpha(@copper, 0.40);
      }

      #network {
          color: @teal_bright;
          background: alpha(@teal, 0.10);
          border-color: alpha(@teal, 0.40);
      }

      #pulseaudio {
          color: @teal_bright;
          background: alpha(@teal, 0.10);
          border-color: alpha(@teal, 0.40);
      }

      #mpd {
          color: @amber;
          background: alpha(@amber, 0.10);
          border-color: alpha(@amber, 0.42);
          text-shadow: 0 0 4px alpha(@amber, 0.40);
      }

      /* state overrides */
      #network.disconnected,
      #pulseaudio.muted {
          color: @text_dim;
          border-color: alpha(@text_dim, 0.40);
          background: transparent;
          text-shadow: none;
      }

      #cpu.warning,
      #memory.warning {
          color: @gold;
          border-color: alpha(@gold, 0.55);
      }

      #cpu.critical,
      #memory.critical {
          color: @copper;
          border-color: alpha(@copper, 0.90);
          animation: pulse 1.1s ease-in-out infinite;
      }

      /* ── tray ───────────────────────────────────────────────────────── */
      #tray {
          background: transparent;
          padding: 0 6px;
          margin: 4px 4px;
          opacity: 0.65;
      }

      #tray > .passive         { opacity: 0.50; }
      #tray > .needs-attention { opacity: 1.00; }

      @keyframes pulse {
          0%   { opacity: 1.0; }
          50%  { opacity: 0.45; }
          100% { opacity: 1.0; }
      }
    '';
  };

      
  # ── MangoWC ───────────────────────────────────────────────────────────────
  xdg.configFile."mango/config.conf".text = ''
    exec-once=waybar
    exec-once=waypaper --restore
    exec-once=lxqt-policykit-agent

    # Gaps
    gappih=5
    gappiv=5
    gappoh=20
    gappov=20

    # Borders
    borderpx=2
    focuscolor=0xc8a96eff
    bordercolor=0x7a5030ff

    # Pywal dynamic colors (overrides the defaults above when present)
    source-optional=~/.cache/wal/colors-mango.conf

    # Decoration
    border_radius=5
    blur=1
    blur_params_num_passes=4
    blur_params_radius=3
    shadows=1
    shadows_size=4
    shadowscolor=0x1a1a1aff

    # Animations
    animations=1

    # Input
    xkb_rules_layout=us
    sloppyfocus=1
    trackpad_natural_scrolling=0
    cursor_theme=Bibata-Modern-Classic
    cursor_size=24

    bind=SUPER,r,reload_config
    bind=SUPER,q,spawn,kitty
    bind=SUPER,c,killclient
    bind=SUPER,m,quit
    bind=SUPER,e,spawn,dolphin
    bind=SUPER,v,togglefloating
    bind=SUPER,d,spawn,rofi -show drun
    bind=SUPER,f,togglefullscreen

    bind=SUPER,left,focusdir,left
    bind=SUPER,right,focusdir,right
    bind=SUPER,up,focusdir,up
    bind=SUPER,down,focusdir,down

    bind=SUPER+SHIFT,t,setlayout,tile
    bind=SUPER+SHIFT,g,setlayout,grid
    bind=SUPER+SHIFT,m,setlayout,monocle
    bind=SUPER+SHIFT,d,setlayout,deck
    bind=SUPER+SHIFT,r,setlayout,scroller

    bind=SUPER,1,view,1,0
    bind=SUPER,2,view,2,0
    bind=SUPER,3,view,3,0
    bind=SUPER,4,view,4,0
    bind=SUPER,5,view,5,0
    bind=SUPER,6,view,6,0
    bind=SUPER,7,view,7,0
    bind=SUPER,8,view,8,0
    bind=SUPER,9,view,9,0
    bind=SUPER,0,view,10,0

    bind=SUPER+SHIFT,1,tag,1,0
    bind=SUPER+SHIFT,2,tag,2,0
    bind=SUPER+SHIFT,3,tag,3,0
    bind=SUPER+SHIFT,4,tag,4,0
    bind=SUPER+SHIFT,5,tag,5,0
    bind=SUPER+SHIFT,6,tag,6,0
    bind=SUPER+SHIFT,7,tag,7,0
    bind=SUPER+SHIFT,8,tag,8,0
    bind=SUPER+SHIFT,9,tag,9,0
    bind=SUPER+SHIFT,0,tag,10,0

    bind=SUPER,s,toggle_scratchpad
    bind=SUPER+SHIFT,s,toggle_scratchpad

    axisbind=SUPER,DOWN,viewtoright_have_client
    axisbind=SUPER,UP,viewtoleft_have_client

    mousebind=SUPER,btn_left,moveresize,curmove
    mousebind=SUPER,btn_right,moveresize,curresize

    bind=NONE,XF86AudioRaiseVolume,spawn,wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
    bind=NONE,XF86AudioLowerVolume,spawn,wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
    bind=NONE,XF86AudioMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
    bind=NONE,XF86AudioMicMute,spawn,wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
    bind=NONE,XF86MonBrightnessUp,spawn,brightnessctl -e4 -n2 set 5%+
    bind=NONE,XF86MonBrightnessDown,spawn,brightnessctl -e4 -n2 set 5%-

    bindl=NONE,XF86AudioNext,spawn,playerctl next
    bindl=NONE,XF86AudioPause,spawn,playerctl play-pause
    bindl=NONE,XF86AudioPlay,spawn,playerctl play-pause
    bindl=NONE,XF86AudioPrev,spawn,playerctl previous

    bind=NONE,Insert,spawn_shell,mkdir -p ~/Pictures/screenshots && grim ~/Pictures/screenshots/$(date +%Y%m%d_%H%M%S).png
    bind=SUPER,Insert,spawn_shell,mkdir -p ~/Pictures/screenshots && grim -g "$(slurp)" ~/Pictures/screenshots/$(date +%Y%m%d_%H%M%S).png
  '';
}
